/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CopilotSeatDetailsAssignee : The assignee that has been granted access to GitHub Copilot.
/// The assignee that has been granted access to GitHub Copilot.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CopilotSeatDetailsAssignee {
    SimpleUser(Box<models::SimpleUser>),
}

impl Default for CopilotSeatDetailsAssignee {
    fn default() -> Self {
        Self::SimpleUser(Default::default())
    }
}

