/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ReposGetContent200Response {
    /// A list of directory items
    ContentDirectory(Vec<models::ContentDirectoryInner>),
    ContentFile(Box<models::ContentFile>),
    ContentSymlink(Box<models::ContentSymlink>),
    ContentSubmodule(Box<models::ContentSubmodule>),
}

impl Default for ReposGetContent200Response {
    fn default() -> Self {
        Self::ContentDirectory(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "file")]
    File,
    #[serde(rename = "symlink")]
    Symlink,
    #[serde(rename = "submodule")]
    Submodule,
}

impl Default for Type {
    fn default() -> Type {
        Self::File
    }
}

