/*
 * GitHub v3 REST API
 *
 * GitHub's v3 REST API.
 *
 * The version of the OpenAPI document: 1.1.4
 *
 * Generated by: https://openapi-generator.tech
 */

use std::fmt::Display;

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SecurityAdvisoriesListGlobalAdvisoriesCwesParameter {
    String(String),
    Array(Vec<String>),
}

impl Default for SecurityAdvisoriesListGlobalAdvisoriesCwesParameter {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

impl Display for SecurityAdvisoriesListGlobalAdvisoriesCwesParameter {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SecurityAdvisoriesListGlobalAdvisoriesCwesParameter::String(s) => write!(f, "{}", s),
            SecurityAdvisoriesListGlobalAdvisoriesCwesParameter::Array(vec) => {
                write!(f, "{}", vec.join(","))
            }
        }
    }
}
